# https://stackoverflow.com/questions/24662571/python-import-csv-to-list
# https://python.doctor/page-apprendre-listes-list-tableaux-tableaux-liste-array-python-cours-debutant
# https://docs.python.org/3/

import argparse
import csv
from xml.etree.ElementTree import Element, SubElement, Comment, ElementTree
# from pprint import pprint
import env
import datetime

IDIR = env.DIR + "Migros/"
print(IDIR)

parser = argparse.ArgumentParser()
parser.add_argument("filename", help="csv IFILE from Migros (path is fixed)")
args = parser.parse_args()
FILE = args.filename
IFILE = IDIR + FILE
print("Nom du fichier en entrée: " + IFILE)

try:
    with open(IFILE, 'r', newline='', encoding='utf8') as IN:
        reader = csv.DictReader(IN, delimiter=';')

        generated_on = str(datetime.datetime.now())
        tickets = Element('tickets')   # élément racine
        tickets.append(Comment('Generated by readTickets.py at ' + generated_on))
#       tickets
#       -- ticket (magasin, caisse, transation, date avec heure)
#       -- -- article
#       -- -- -- texte
#       -- -- -- quantité
#       -- -- -- rabais
#       -- -- -- prix
        oldGroup = ''
        group = ''
        count = 0
        for row in reader:
            # pprint(row): Datum;Zeit;Filiale;Kassennummer;Transaktionsnummer;Artikel;Menge;Aktion;Umsatz
            Date = row['Datum']
            Heure = row['Zeit']
            Magasin = row['Filiale']
            Caisse = row['Kassennummer']
            Transaction = row['Transaktionsnummer']
            Article = row['Artikel']
            Quantite = row['Menge']
            Rabais = row['Aktion']
            Prix = row['Umsatz']
            group = Magasin + Caisse + Transaction
            if group != oldGroup:  # nouveau ticket lors du changement de groupe
                oldGroup = group
                ticket = SubElement(tickets, 'ticket')
                ticket.set('magasin', Magasin)
                ticket.set('caisse', Caisse)
                ticket.set('transaction', Transaction)
                ticket.set('date', Date + ' ' + Heure)
                count = count + 1
            article = SubElement(ticket, 'article')
            texte = SubElement(article, 'texte')
            texte.text = Article
            texte = SubElement(article, 'texte')
            quantite = SubElement(article, 'quantite')
            quantite.text = Quantite
            rabais = SubElement(article, 'rabais')
            rabais.text = Rabais
            prix = SubElement(article, 'prix')
            prix.text = Prix

except FileNotFoundError:
    print("Ce fichier n'existe pas: '" + IFILE + "'")
    exit(1)

#  écrire les transactions normalisées sur fichier
OFILE = env.ODIR + FILE.replace('.csv', '.xml')
OFILE = IFILE.replace('.csv', '.xml')
ElementTree(tickets).write(OFILE, encoding='utf-8')

# with open(OFILE, 'w', newline='', encoding='utf8') as OUT:
#     s = XET.tostring(tickets, encoding='unicode', method='xml')
#     r = ElementTree(s)
#     r.write(sys.stdout)
# print(tostring(tickets, 'utf-8'))

print("Fichier de sortie xml: ", OFILE)
print("Nombre de tickets: ", count)
